### ISSUE TITLE
Pin assignment

### ISSUE THREAD

**Issue by calston** [dhylands/python_lcd#11]
Hi

Do you have some indication of the expected pin assignment between the PCF8574 and the LCD?

**Comment by calston** [comment]
Nevermind, figured it out from the link

**Comment by dhylands** [comment]
Here's the assignment for the backpack I used:
https://github.com/dhylands/python_lcd/blob/master/lcd/pyb_i2c_lcd.py#L11-L15

It's formed as masks/shifts rather than pin numbers.
Pin 0 - RS
Pin 1 - RW
Pin 2 - E
Pin 3 - Backlight
Pins 4-7 - Data0 thru Data3
